#!/bin/bash

# launch script for HW-HTML
# script version 1.1

# install dir
install_dir="$(dirname "$0")"

# resolve arguments to absolute paths
i=1
for arg in "$@"
do
	if [[ ! $arg == -* ]]
	then
		args[i-1]="$(realpath "${!i}")"
	else
		args[i-1]="${!i}"
	fi
	
	i=$(($i+1))
done

# cd to install dir to find default.css
cd $install_dir

java -jar "$install_dir/HW-HTML.jar" "${args[@]}"
